name = "404--society"
main = "src/worker.js"
compatibility_date = "2025-09-01"
keep_vars = true

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "404-society-db"
database_id = "abf53cc8-6e4e-4b55-93a1-e6729d5e53d1"

[vars]
CASHFREE_ENV = "sandbox"
QIKINK_ENV = "sandbox"
